import type { ExamCategory, LabExam } from "./types";

export const EXAM_CATEGORIES: ExamCategory[] = [
  { key: "hematologia", label: "Hematologia", icon: "🩸" },
  { key: "bioquimica", label: "Bioquímica", icon: "🧪" },
  { key: "urinalise", label: "Urinálise", icon: "💧" },
  { key: "parasitologia", label: "Parasitologia", icon: "🔬" },
  { key: "microbiologia", label: "Microbiologia", icon: "🦠" },
  { key: "endocrinologia", label: "Endocrinologia", icon: "⚗️" },
  { key: "coagulacao", label: "Coagulação", icon: "🩹" },
  { key: "imunologia", label: "Imunologia / Sorologia", icon: "🛡️" },
  { key: "hepatite", label: "Função Hepática / Hepatite", icon: "🫁" },
  { key: "cardiologia", label: "Cardiologia", icon: "❤️" },
  { key: "imagem", label: "Imagem", icon: "📷" },
  { key: "citologia", label: "Citologia / Anatomia Patológica", icon: "🔎" },
  { key: "outros", label: "Outros", icon: "📋" },
];

export const LAB_EXAMS: LabExam[] = [
  // ═══════════════════════════════════════════════════════════
  // HEMATOLOGIA
  // ═══════════════════════════════════════════════════════════
  {
    id: "hemograma-completo",
    name: "Hemograma Completo",
    category: "hematologia",
    description: "Série vermelha, branca e plaquetária",
    instructions: "Jejum não necessário",
  },
  {
    id: "hemacia",
    name: "Contagem de Hemácias",
    category: "hematologia",
    description: "Contagem de eritrócitos",
    instructions: "",
  },
  {
    id: "hemoglobina",
    name: "Hemoglobina",
    category: "hematologia",
    description: "Dosagem de hemoglobina",
    instructions: "",
  },
  {
    id: "hematocrito",
    name: "Hematócrito",
    category: "hematologia",
    description: "Volume globular",
    instructions: "",
  },
  {
    id: "leucograma",
    name: "Leucograma",
    category: "hematologia",
    description: "Contagem total e diferencial de leucócitos",
    instructions: "",
  },
  {
    id: "plaquetas",
    name: "Plaquetas",
    category: "hematologia",
    description: "Contagem de plaquetas",
    instructions: "",
  },
  {
    id: "reticulocitos",
    name: "Reticulócitos",
    category: "hematologia",
    description: "Contagem de reticulócitos",
    instructions: "",
  },
  {
    id: "vhs",
    name: "VHS (Velocidade de Hemossedimentação)",
    category: "hematologia",
    description: "Velocidade de hemossedimentação",
    instructions: "",
  },
  {
    id: "ferritina",
    name: "Ferritina",
    category: "hematologia",
    description: "Dosagem de ferritina sérica",
    instructions: "Jejum de 4h",
  },
  {
    id: "ferro-serico",
    name: "Ferro Sérico",
    category: "hematologia",
    description: "Dosagem de ferro sérico",
    instructions: "Jejum de 8h, coletar pela manhã",
  },
  {
    id: "transferrina",
    name: "Transferrina",
    category: "hematologia",
    description: "Dosagem de transferrina",
    instructions: "Jejum de 4h",
  },
  {
    id: "capacidade-total-ligacao-ferro",
    name: "Capacidade Total de Ligação do Ferro (TIBC)",
    category: "hematologia",
    description: "TIBC",
    instructions: "Jejum de 8h",
  },
  {
    id: "saturacao-transferrina",
    name: "Saturação da Transferrina",
    category: "hematologia",
    description: "Índice de saturação da transferrina",
    instructions: "Jejum de 8h",
  },
  {
    id: "vitamina-b12",
    name: "Vitamina B12",
    category: "hematologia",
    description: "Dosagem de cobalamina",
    instructions: "Jejum de 8h",
  },
  {
    id: "acido-folico",
    name: "Ácido Fólico (Folato)",
    category: "hematologia",
    description: "Dosagem de folato sérico",
    instructions: "Jejum de 8h",
  },
  {
    id: "eletroforese-hemoglobina",
    name: "Eletroforese de Hemoglobina",
    category: "hematologia",
    description: "Pesquisa de hemoglobinas anormais",
    instructions: "",
  },
  {
    id: "teste-falcizacao",
    name: "Teste de Falcização",
    category: "hematologia",
    description: "Pesquisa de hemácia falciforme",
    instructions: "",
  },
  {
    id: "esfregaco-sanguineo",
    name: "Esfregaço de Sangue Periférico",
    category: "hematologia",
    description: "Morfologia de hemácias, leucócitos e plaquetas",
    instructions: "",
  },
  {
    id: "grupo-sanguineo-fator-rh",
    name: "Grupo Sanguíneo + Fator Rh",
    category: "hematologia",
    description: "Tipagem ABO e Rh",
    instructions: "",
  },
  {
    id: "prova-cruzada",
    name: "Prova Cruzada (Tipagem e Prova)",
    category: "hematologia",
    description: "Compatibilidade sanguínea",
    instructions: "",
  },
  {
    id: "coombs-direto",
    name: "Teste de Coombs Direto",
    category: "hematologia",
    description: "Pesquisa de anticorpos anti-hemácias",
    instructions: "",
  },
  {
    id: "coombs-indireto",
    name: "Teste de Coombs Indireto",
    category: "hematologia",
    description: "Pesquisa de anticorpos séricos irregulares",
    instructions: "",
  },

  // ═══════════════════════════════════════════════════════════
  // BIOQUÍMICA
  // ═══════════════════════════════════════════════════════════
  {
    id: "glicemia-jejum",
    name: "Glicemia em Jejum",
    category: "bioquimica",
    description: "Glicose em jejum",
    instructions: "Jejum de 8-12h",
  },
  {
    id: "glicemia-pos-prandial",
    name: "Glicemia Pós-Prandial",
    category: "bioquimica",
    description: "Glicose 2h após refeição",
    instructions: "Coletar 2h após início da refeição",
  },
  {
    id: "curva-glicemica",
    name: "Teste Oral de Tolerância à Glicose (TTG 75g)",
    category: "bioquimica",
    description: "Curva glicêmica com 75g de glicose",
    instructions: "Jejum de 8-12h. Coletar jejum, 1h e 2h após sobrecarga.",
  },
  {
    id: "hemoglobina-glicada",
    name: "Hemoglobina Glicada (HbA1c)",
    category: "bioquimica",
    description: "Média glicêmica dos últimos 2-3 meses",
    instructions: "Jejum não necessário",
  },
  {
    id: "ureia",
    name: "Ureia",
    category: "bioquimica",
    description: "Dosagem de ureia sérica",
    instructions: "Jejum de 4h",
  },
  {
    id: "creatinina",
    name: "Creatinina",
    category: "bioquimica",
    description: "Dosagem de creatinina sérica",
    instructions: "Jejum de 4h",
  },
  {
    id: "tfg",
    name: "Taxa de Filtração Glomerular (TFG)",
    category: "bioquimica",
    description: "Cálculo da TFG (CKD-EPI)",
    instructions: "Com creatinina",
  },
  {
    id: "acido-urico",
    name: "Ácido Úrico",
    category: "bioquimica",
    description: "Dosagem de ácido úrico sérico",
    instructions: "Jejum de 8h, evitar álcool 24h antes",
  },
  {
    id: "colesterol-total",
    name: "Colesterol Total",
    category: "bioquimica",
    description: "Dosagem de colesterol total",
    instructions: "Jejum de 12h",
  },
  {
    id: "hdl",
    name: "HDL-Colesterol",
    category: "bioquimica",
    description: "Colesterol HDL",
    instructions: "Jejum de 12h",
  },
  {
    id: "ldl",
    name: "LDL-Colesterol",
    category: "bioquimica",
    description: "Colesterol LDL (calculado)",
    instructions: "Jejum de 12h",
  },
  {
    id: "vldl",
    name: "VLDL-Colesterol",
    category: "bioquimica",
    description: "Colesterol VLDL",
    instructions: "Jejum de 12h",
  },
  {
    id: "triglicerideos",
    name: "Triglicerídeos",
    category: "bioquimica",
    description: "Dosagem de triglicerídeos",
    instructions: "Jejum de 12h",
  },
  {
    id: "lipidograma",
    name: "Lipidograma Completo",
    category: "bioquimica",
    description: "Colesterol total, HDL, LDL, VLDL e triglicerídeos",
    instructions: "Jejum de 12h",
  },
  {
    id: "proteinas-totais",
    name: "Proteínas Totais e Frações",
    category: "bioquimica",
    description: "Proteínas totais, albumina e globulinas",
    instructions: "Jejum de 4h",
  },
  {
    id: "albumina",
    name: "Albumina",
    category: "bioquimica",
    description: "Dosagem de albumina sérica",
    instructions: "Jejum de 4h",
  },
  {
    id: "sodio",
    name: "Sódio",
    category: "bioquimica",
    description: "Dosagem de sódio sérico",
    instructions: "",
  },
  {
    id: "potassio",
    name: "Potássio",
    category: "bioquimica",
    description: "Dosagem de potássio sérico",
    instructions: "",
  },
  {
    id: "calcio",
    name: "Cálcio Total",
    category: "bioquimica",
    description: "Dosagem de cálcio sérico total",
    instructions: "Jejum de 4h",
  },
  {
    id: "calcio-ionico",
    name: "Cálcio Iônico",
    category: "bioquimica",
    description: "Cálcio ionizado",
    instructions: "Coletar em tubo heparinizado",
  },
  {
    id: "fosforo",
    name: "Fósforo",
    category: "bioquimica",
    description: "Dosagem de fósforo sérico",
    instructions: "Jejum de 4h",
  },
  {
    id: "magnesio",
    name: "Magnésio",
    category: "bioquimica",
    description: "Dosagem de magnésio sérico",
    instructions: "Jejum de 4h",
  },
  {
    id: "cloro",
    name: "Cloro",
    category: "bioquimica",
    description: "Dosagem de cloro sérico",
    instructions: "",
  },
  {
    id: "eletrólitos",
    name: "Eletrólitos (Na, K, Cl)",
    category: "bioquimica",
    description: "Sódio, potássio e cloro",
    instructions: "",
  },
  {
    id: "bilirrubinas",
    name: "Bilirrubinas (Total e Frações)",
    category: "bioquimica",
    description: "Bilirrubina total, direta e indireta",
    instructions: "Jejum de 4h",
  },
  {
    id: "tgo-ast",
    name: "TGO/AST (Transaminase Oxalacética)",
    category: "bioquimica",
    description: "Aspartato aminotransferase",
    instructions: "Jejum de 4h",
  },
  {
    id: "tgp-alt",
    name: "TGP/ALT (Transaminase Pirúvica)",
    category: "bioquimica",
    description: "Alanina aminotransferase",
    instructions: "Jejum de 4h",
  },
  {
    id: "gama-gt",
    name: "Gama-GT (Gama-Glutamil Transferase)",
    category: "bioquimica",
    description: "GGT",
    instructions: "Jejum de 8h, evitar álcool 24h antes",
  },
  {
    id: "fosfatase-alcalina",
    name: "Fosfatase Alcalina",
    category: "bioquimica",
    description: "Dosagem de FA",
    instructions: "Jejum de 8h",
  },
  {
    id: "amilase",
    name: "Amilase",
    category: "bioquimica",
    description: "Dosagem de amilase sérica",
    instructions: "Jejum de 4h",
  },
  {
    id: "lipase",
    name: "Lipase",
    category: "bioquimica",
    description: "Dosagem de lipase sérica",
    instructions: "Jejum de 8h",
  },
  {
    id: "ldh",
    name: "LDH (Lactato Desidrogenase)",
    category: "bioquimica",
    description: "Dosagem de LDH",
    instructions: "Jejum de 4h",
  },
  {
    id: "cpk",
    name: "CPK (Creatino Quinase Total)",
    category: "bioquimica",
    description: "Creatino quinase total",
    instructions: "Evitar exercício físico 48h antes",
  },
  {
    id: "cpk-mb",
    name: "CPK-MB",
    category: "bioquimica",
    description: "Fração MB da creatino quinase",
    instructions: "",
  },
  {
    id: "troponina",
    name: "Troponina",
    category: "bioquimica",
    description: "Troponina I ou T cardíaca",
    instructions: "",
  },
  {
    id: "mioglobina",
    name: "Mioglobina",
    category: "bioquimica",
    description: "Dosagem de mioglobina sérica",
    instructions: "",
  },
  {
    id: "proteina-c-reativa",
    name: "Proteína C-Reativa (PCR)",
    category: "bioquimica",
    description: "PCR quantitativo",
    instructions: "",
  },
  {
    id: "pcr-ultrassensivel",
    name: "PCR Ultrassensível",
    category: "bioquimica",
    description: "PCR para risco cardiovascular",
    instructions: "",
  },
  {
    id: "procalcitonina",
    name: "Procalcitonina",
    category: "bioquimica",
    description: "Marcador de infecção bacteriana",
    instructions: "",
  },

  // ═══════════════════════════════════════════════════════════
  // URINÁLISE
  // ═══════════════════════════════════════════════════════════
  {
    id: "eas",
    name: "EAS (Elementos Anormais + Sedimentoscopia)",
    category: "urinalise",
    description: "Urina tipo I",
    instructions: "Primeira urina da manhã, jato médio",
  },
  {
    id: "urina-tipo-1",
    name: "Urina Tipo I",
    category: "urinalise",
    description: "Sumário urinário com sedimentoscopia",
    instructions: "Primeira urina da manhã, jato médio",
  },
  {
    id: "urocultura",
    name: "Urocultura com Antibiograma",
    category: "urinalise",
    description: "Cultura de urina + teste de sensibilidade",
    instructions: "Primeira urina da manhã, jato médio, sem uso prévio de ATB",
  },
  {
    id: "proteinuria-24h",
    name: "Proteinuria de 24 horas",
    category: "urinalise",
    description: "Proteína urinária em coleta de 24h",
    instructions: "Coletar toda urina em 24h",
  },
  {
    id: "relacao-albumina-creatinina",
    name: "Relação Albumina/Creatinina Urinária",
    category: "urinalise",
    description: "Microalbuminúria em amostra isolada",
    instructions: "Primeira urina da manhã",
  },
  {
    id: "microalbuminuria",
    name: "Microalbuminúria",
    category: "urinalise",
    description: "Dosagem de albumina urinária",
    instructions: "Urina de 24h ou primeira urina da manhã",
  },
  {
    id: "clearance-creatinina",
    name: "Clearance de Creatinina",
    category: "urinalise",
    description: "Depuração de creatinina em urina de 24h",
    instructions: "Coletar toda urina em 24h + coleta de sangue",
  },
  {
    id: "osmolalidade-urina",
    name: "Osmolalidade Urinária",
    category: "urinalise",
    description: "Capacidade de concentração urinária",
    instructions: "",
  },
  {
    id: "eletroforese-proteinas-urina",
    name: "Eletroforese de Proteínas Urinárias",
    category: "urinalise",
    description: "Proteinuria seletiva e não seletiva",
    instructions: "Urina de 24h",
  },
  {
    id: "citologia-urinaria",
    name: "Citologia Urinária (Pesquisa de Células Neoplásicas)",
    category: "urinalise",
    description: "Pesquisa de células neoplásicas na urina",
    instructions: "Urina de 24h ou primeira urina da manhã",
  },
  {
    id: "baciloscopia-urina",
    name: "Baciloscopia de Urina (BAAR)",
    category: "urinalise",
    description: "Pesquisa de bacilo álcool-ácido resistente",
    instructions: "Primeira urina da manhã, 3 amostras consecutivas",
  },

  // ═══════════════════════════════════════════════════════════
  // PARASITOLOGIA
  // ═══════════════════════════════════════════════════════════
  {
    id: "parasitologico-fezes",
    name: "Parasitológico de Fezes",
    category: "parasitologia",
    description: "Pesquisa de ovos, cistos e larvas",
    instructions: "3 amostras em dias alternados",
  },
  {
    id: "coprocultura",
    name: "Coprocultura",
    category: "parasitologia",
    description: "Cultura de fezes",
    instructions: "Sem uso prévio de ATB",
  },
  {
    id: "sangue-oculto",
    name: "Pesquisa de Sangue Oculto nas Fezes",
    category: "parasitologia",
    description: "Teste de sangue oculto",
    instructions: "Evitar carne vermelha 3 dias antes",
  },
  {
    id: "teste-rapido-giardia",
    name: "Pesquisa de Giardia nas Fezes",
    category: "parasitologia",
    description: "Antígeno de Giardia",
    instructions: "",
  },
  {
    id: "pesquisa-ameba",
    name: "Pesquisa de Entamoeba histolytica",
    category: "parasitologia",
    description: "Pesquisa de E. histolytica nas fezes",
    instructions: "",
  },
  {
    id: "scotch-test",
    name: "Scotch Test (Pesquisa de Enterobius)",
    category: "parasitologia",
    description: "Pesquisa de ovos de oxiúrus",
    instructions: "Realizar pela manhã antes de higiene",
  },
  {
    id: "gotas-espessas-malaria",
    name: "Gotas Espessas (Pesquisa de Plasmódio)",
    category: "parasitologia",
    description: "Pesquisa de plasmódio em sangue periférico",
    instructions: "Coletar durante pico febril",
  },
  {
    id: "teste-rapido-malaria",
    name: "Teste Rápido para Malária",
    category: "parasitologia",
    description: "Teste imunocromatográfico para malária",
    instructions: "",
  },
  {
    id: "pesquisa-schistosoma",
    name: "Pesquisa de Schistosoma (Método de Kato-Katz)",
    category: "parasitologia",
    description: "Pesquisa de ovos de Schistosoma",
    instructions: "",
  },

  // ═══════════════════════════════════════════════════════════
  // MICROBIOLOGIA
  // ═══════════════════════════════════════════════════════════
  {
    id: "hemocultura",
    name: "Hemocultura",
    category: "microbiologia",
    description: "Cultura de sangue (aeróbio e anaeróbio)",
    instructions: "Coletar antes de ATB, 2-3 amostras",
  },
  {
    id: "cultura-secrecao",
    name: "Cultura de Secreção com Antibiograma",
    category: "microbiologia",
    description: "Cultura de secreção + teste de sensibilidade",
    instructions: "Sem uso prévio de ATB tópico",
  },
  {
    id: "cultura-orofaringe",
    name: "Cultura de Orofaringe com Antibiograma",
    category: "microbiologia",
    description: "Swab de garganta + cultura",
    instructions: "Sem uso prévio de ATB",
  },
  {
    id: "cultura-nasal",
    name: "Cultura de Narina com Antibiograma",
    category: "microbiologia",
    description: "Swab nasal + cultura",
    instructions: "",
  },
  {
    id: "cultura-otologica",
    name: "Cultura de Secreção Otologica",
    category: "microbiologia",
    description: "Cultura de secreção de ouvido",
    instructions: "",
  },
  {
    id: "cultura-ocular",
    name: "Cultura de Secreção Ocular",
    category: "microbiologia",
    description: "Swab conjuntival + cultura",
    instructions: "",
  },
  {
    id: "baciloscopia-secrecao",
    name: "Baciloscopia de Secreção (Gram)",
    category: "microbiologia",
    description: "Coloração de Gram de secreção",
    instructions: "",
  },
  {
    id: "pesquisa-fungos",
    name: "Pesquisa de Fungos (Micológico Direto + Cultura)",
    category: "microbiologia",
    description: "Exame micológico direto e cultura de fungos",
    instructions: "Suspender antifúngicos 7 dias antes",
  },
  {
    id: "pesquisa-baar-escarro",
    name: "Pesquisa de BAAR em Escarro",
    category: "microbiologia",
    description: "Baciloscopia de escarro (Ziehl-Neelsen)",
    instructions: "3 amostras: coleta inicial, 24h e 48h",
  },
  {
    id: "cultura-mycobacterium",
    name: "Cultura de Mycobacterium (MGIT)",
    category: "microbiologia",
    description: "Cultura de micobactéria",
    instructions: "3 amostras de escarro",
  },
  {
    id: "gene-xpert-tb",
    name: "GeneXpert MTB/RIF (TB + Resistência Rifampicina)",
    category: "microbiologia",
    description: "Teste molecular rápido para TB",
    instructions: "Amostra de escarro",
  },
  {
    id: "cultura-liquido",
    name: "Cultura de Líquido (CEFALORRAQUIDIANO, SINOVIAL, etc.)",
    category: "microbiologia",
    description: "Cultura de líquidos orgânicos",
    instructions: "Coletar antes de ATB",
  },

  // ═══════════════════════════════════════════════════════════
  // ENDOCRINOLOGIA
  // ═══════════════════════════════════════════════════════════
  {
    id: "tsh",
    name: "TSH",
    category: "endocrinologia",
    description: "Hormônio tireoestimulante",
    instructions: "",
  },
  {
    id: "t4-livre",
    name: "T4 Livre",
    category: "endocrinologia",
    description: "Tiroxina livre",
    instructions: "",
  },
  {
    id: "t3",
    name: "T3 Total",
    category: "endocrinologia",
    description: "Triiodotironina total",
    instructions: "",
  },
  {
    id: "t3-livre",
    name: "T3 Livre",
    category: "endocrinologia",
    description: "Triiodotironina livre",
    instructions: "",
  },
  {
    id: "t4-total",
    name: "T4 Total",
    category: "endocrinologia",
    description: "Tiroxina total",
    instructions: "",
  },
  {
    id: "perfil-tireoidiano",
    name: "Perfil Tireoidiano (TSH + T4L + T3L)",
    category: "endocrinologia",
    description: "Avaliação completa da tireoide",
    instructions: "",
  },
  {
    id: "anti-tpo",
    name: "Anti-TPO (Anticorpo Antiperoxidase Tireoidiana)",
    category: "endocrinologia",
    description: "Autoimunidade tireoidiana",
    instructions: "",
  },
  {
    id: "anti-tg",
    name: "Anti-TG (Anticorpo Antitireoglobulina)",
    category: "endocrinologia",
    description: "Autoimunidade tireoidiana",
    instructions: "",
  },
  {
    id: "trab",
    name: "TRAb (Anticorpo Antirreceptor de TSH)",
    category: "endocrinologia",
    description: "Diagnóstico de Doença de Graves",
    instructions: "",
  },
  {
    id: "tiroglobulina",
    name: "Tireoglobulina",
    category: "endocrinologia",
    description: "Marcador tumoral de tireoide",
    instructions: "",
  },
  {
    id: "cortisol-manha",
    name: "Cortisol Matinal",
    category: "endocrinologia",
    description: "Dosagem de cortisol às 8h",
    instructions: "Coletar entre 7-9h, jejum de 4h",
  },
  {
    id: "cortisol-noite",
    name: "Cortisol Noturno",
    category: "endocrinologia",
    description: "Dosagem de cortisol às 23h",
    instructions: "Coletar às 23h",
  },
  {
    id: "cortisol-livre-urina",
    name: "Cortisol Livre Urinário (24h)",
    category: "endocrinologia",
    description: "Cortisol livre em urina de 24h",
    instructions: "Coletar toda urina em 24h",
  },
  {
    id: "acth",
    name: "ACTH",
    category: "endocrinologia",
    description: "Hormônio adrenocorticotrófico",
    instructions: "Coletar entre 7-9h, tubo refrigerado",
  },
  {
    id: "dhea-s",
    name: "DHEA-S (Sulfato de Deidroepiandrosterona)",
    category: "endocrinologia",
    description: "Andrógeno adrenal",
    instructions: "Jejum de 4h",
  },
  {
    id: "testosterona-total",
    name: "Testosterona Total",
    category: "endocrinologia",
    description: "Dosagem de testosterona total",
    instructions: "Coletar entre 7-10h, jejum de 4h",
  },
  {
    id: "testosterona-livre",
    name: "Testosterona Livre",
    category: "endocrinologia",
    description: "Dosagem de testosterona livre",
    instructions: "Coletar entre 7-10h",
  },
  {
    id: "lh",
    name: "LH (Hormônio Luteinizante)",
    category: "endocrinologia",
    description: "Dosagem de LH",
    instructions: "Informar dia do ciclo menstrual",
  },
  {
    id: "fsh",
    name: "FSH (Hormônio Folículo-Estimulante)",
    category: "endocrinologia",
    description: "Dosagem de FSH",
    instructions: "Informar dia do ciclo menstrual",
  },
  {
    id: "estradiol",
    name: "Estradiol",
    category: "endocrinologia",
    description: "Dosagem de estradiol",
    instructions: "Informar dia do ciclo menstrual",
  },
  {
    id: "progesterona",
    name: "Progesterona",
    category: "endocrinologia",
    description: "Dosagem de progesterona",
    instructions: "Informar dia do ciclo menstrual",
  },
  {
    id: "prolactina",
    name: "Prolactina",
    category: "endocrinologia",
    description: "Dosagem de prolactina",
    instructions: "Jejum de 8h, repouso 30min antes da coleta, evitar estresse",
  },
  {
    id: "gh",
    name: "GH (Hormônio do Crescimento)",
    category: "endocrinologia",
    description: "Dosagem de GH",
    instructions: "Jejum de 8h, repouso 30min antes",
  },
  {
    id: "igf-1",
    name: "IGF-1 (Fator de Crescimento Semelhante à Insulina)",
    category: "endocrinologia",
    description: "Dosagem de IGF-1",
    instructions: "Jejum de 4h",
  },
  {
    id: "paratormonio",
    name: "PTH (Paratormônio)",
    category: "endocrinologia",
    description: "Hormônio paratireoidiano intacto",
    instructions: "Jejum de 8h",
  },
  {
    id: "vitamina-d",
    name: "Vitamina D (25-OH)",
    category: "endocrinologia",
    description: "25-hidroxivitamina D",
    instructions: "Jejum de 4h",
  },
  {
    id: "insulina",
    name: "Insulina",
    category: "endocrinologia",
    description: "Dosagem de insulina sérica",
    instructions: "Jejum de 8h",
  },
  {
    id: "peptideo-c",
    name: "Peptídeo C",
    category: "endocrinologia",
    description: "Avaliação da reserva pancreática",
    instructions: "Jejum de 8h",
  },
  {
    id: "aldosterona",
    name: "Aldosterona",
    category: "endocrinologia",
    description: "Dosagem de aldosterona",
    instructions: "Coletar em pé ou deitado conforme orientação",
  },
  {
    id: "renina",
    name: "Renina",
    category: "endocrinologia",
    description: "Dosagem de renina plasmática",
    instructions: "Coletar em pé ou deitado conforme orientação",
  },
  {
    id: "ratio-aldosterona-renina",
    name: "Relação Aldosterona/Renina (RAR)",
    category: "endocrinologia",
    description: "Rastreio de hiperaldosteronismo",
    instructions: "",
  },
  {
    id: "metanefrinas",
    name: "Metanefrinas Plasmáticas ou Urinárias",
    category: "endocrinologia",
    description: "Rastreio de feocromocitoma",
    instructions: "Jejum de 8h, evitar café e estresse",
  },
  {
    id: "ca-125",
    name: "CA-125",
    category: "endocrinologia",
    description: "Marcador tumoral ovariano",
    instructions: "",
  },
  {
    id: "ca-19-9",
    name: "CA 19-9",
    category: "endocrinologia",
    description: "Marcador tumoral pancreático/gástrico",
    instructions: "",
  },
  {
    id: "cea",
    name: "CEA (Antígeno Carcinoembrionário)",
    category: "endocrinologia",
    description: "Marcador tumoral colorretal",
    instructions: "",
  },
  {
    id: "psa-total",
    name: "PSA Total (Antígeno Prostático Específico)",
    category: "endocrinologia",
    description: "Rastreio de câncer de próstata",
    instructions: "Evitar ejaculação 48h antes",
  },
  {
    id: "psa-livre",
    name: "PSA Livre",
    category: "endocrinologia",
    description: "Fração livre do PSA",
    instructions: "Evitar ejaculação 48h antes",
  },
  {
    id: "afp",
    name: "AFP (Alfa-Fetoproteína)",
    category: "endocrinologia",
    description: "Marcador tumoral hepático/germinativo",
    instructions: "",
  },

  // ═══════════════════════════════════════════════════════════
  // COAGULAÇÃO
  // ═══════════════════════════════════════════════════════════
  {
    id: "tp",
    name: "TP (Tempo de Protrombina)",
    category: "coagulacao",
    description: "Tempo de protrombina",
    instructions: "Jejum de 4h",
  },
  {
    id: "inr",
    name: "INR (Razão Normalizada Internacional)",
    category: "coagulacao",
    description: "Controle de anticoagulação oral",
    instructions: "Jejum de 4h",
  },
  {
    id: "tttpa",
    name: "TTPA (Tempo de Tromboplastina Parcial Ativada)",
    category: "coagulacao",
    description: "Tempo de tromboplastina parcial ativada",
    instructions: "Jejum de 4h",
  },
  {
    id: "tempo-sangramento",
    name: "Tempo de Sangramento",
    category: "coagulacao",
    description: "Teste de função plaquetária",
    instructions: "",
  },
  {
    id: "fibrinogenio",
    name: "Fibrinogênio",
    category: "coagulacao",
    description: "Dosagem de fibrinogênio",
    instructions: "Jejum de 4h",
  },
  {
    id: "d-dimero",
    name: "D-Dímero",
    category: "coagulacao",
    description: "Produto de degradação da fibrina",
    instructions: "Jejum de 4h",
  },
  {
    id: "antitrombina",
    name: "Antitrombina III",
    category: "coagulacao",
    description: "Dosagem de antitrombina",
    instructions: "Jejum de 4h",
  },
  {
    id: "proteina-c",
    name: "Proteína C",
    category: "coagulacao",
    description: "Dosagem de proteína C",
    instructions: "Jejum de 4h",
  },
  {
    id: "proteina-s",
    name: "Proteína S",
    category: "coagulacao",
    description: "Dosagem de proteína S",
    instructions: "Jejum de 4h",
  },
  {
    id: "fator-v-leiden",
    name: "Fator V Leiden",
    category: "coagulacao",
    description: "Pesquisa de mutação do fator V",
    instructions: "",
  },
  {
    id: "lupus-anticoagulante",
    name: "Anticoagulante Lúpico",
    category: "coagulacao",
    description: "Pesquisa de anticoagulante lúpico",
    instructions: "Suspender anticoagulantes se possível",
  },
  {
    id: "anticardiolipina",
    name: "Anticardiolipina (IgG e IgM)",
    category: "coagulacao",
    description: "Anticorpos anticardiolipina",
    instructions: "",
  },

  // ═══════════════════════════════════════════════════════════
  // IMUNOLOGIA / SOROLOGIA
  // ═══════════════════════════════════════════════════════════
  {
    id: "hiv-1-2",
    name: "Anti-HIV 1 e 2",
    category: "imunologia",
    description: "Sorologia para HIV",
    instructions: "",
  },
  {
    id: "hbsag",
    name: "HBsAg (Antígeno de Superfície Hepatite B)",
    category: "imunologia",
    description: "Marcador de infecção por hepatite B",
    instructions: "",
  },
  {
    id: "anti-hbs",
    name: "Anti-HBs (Anticorpo Anti-Antígeno de Superfície)",
    category: "imunologia",
    description: "Imunidade contra hepatite B",
    instructions: "",
  },
  {
    id: "anti-hbc",
    name: "Anti-HBc (Anticorpo Anti-Core Hepatite B)",
    category: "imunologia",
    description: "Exposição prévia ao HBV",
    instructions: "",
  },
  {
    id: "hbeag",
    name: "HBeAg (Antígeno E Hepatite B)",
    category: "imunologia",
    description: "Marcador de replicação viral do HBV",
    instructions: "",
  },
  {
    id: "anti-hbe",
    name: "Anti-HBe",
    category: "imunologia",
    description: "Soroconversão do HBeAg",
    instructions: "",
  },
  {
    id: "anti-hcv",
    name: "Anti-HCV (Hepatite C)",
    category: "imunologia",
    description: "Sorologia para hepatite C",
    instructions: "",
  },
  {
    id: "carga-viral-hcv",
    name: "Carga Viral HCV (PCR Quantitativo)",
    category: "imunologia",
    description: "RNA do HCV quantitativo",
    instructions: "",
  },
  {
    id: "vdrl",
    name: "VDRL (Sorologia para Sífilis)",
    category: "imunologia",
    description: "Teste não treponêmico para sífilis",
    instructions: "",
  },
  {
    id: "fta-abs",
    name: "FTA-ABS (Sorologia Treponêmica)",
    category: "imunologia",
    description: "Teste treponêmico para sífilis",
    instructions: "",
  },
  {
    id: "toxoplasmose-igg",
    name: "Toxoplasmose - IgG",
    category: "imunologia",
    description: "Anticorpos IgG anti-Toxoplasma",
    instructions: "",
  },
  {
    id: "toxoplasmose-igm",
    name: "Toxoplasmose - IgM",
    category: "imunologia",
    description: "Anticorpos IgM anti-Toxoplasma",
    instructions: "",
  },
  {
    id: "toxoplasmose-avidex",
    name: "Toxoplasmose - Avidex de IgG",
    category: "imunologia",
    description: "Avididade de IgG anti-Toxoplasma",
    instructions: "",
  },
  {
    id: "rubéola-igg",
    name: "Rubéola - IgG",
    category: "imunologia",
    description: "Anticorpos IgG anti-rubéola",
    instructions: "",
  },
  {
    id: "rubéola-igm",
    name: "Rubéola - IgM",
    category: "imunologia",
    description: "Anticorpos IgM anti-rubéola",
    instructions: "",
  },
  {
    id: "citomegalovirus-igg",
    name: "Citomegalovírus - IgG",
    category: "imunologia",
    description: "Anticorpos IgG anti-CMV",
    instructions: "",
  },
  {
    id: "citomegalovirus-igm",
    name: "Citomegalovírus - IgM",
    category: "imunologia",
    description: "Anticorpos IgM anti-CMV",
    instructions: "",
  },
  {
    id: "herpes-igg",
    name: "Herpes Simples - IgG (Tipo 1 e 2)",
    category: "imunologia",
    description: "Anticorpos IgG anti-HSV",
    instructions: "",
  },
  {
    id: "herpes-igm",
    name: "Herpes Simples - IgM (Tipo 1 e 2)",
    category: "imunologia",
    description: "Anticorpos IgM anti-HSV",
    instructions: "",
  },
  {
    id: "varicela-igg",
    name: "Varicela (Catapora) - IgG",
    category: "imunologia",
    description: "Anticorpos IgG anti-VZV",
    instructions: "",
  },
  {
    id: "varicela-igm",
    name: "Varicela (Catapora) - IgM",
    category: "imunologia",
    description: "Anticorpos IgM anti-VZV",
    instructions: "",
  },
  {
    id: "dengue-ns1",
    name: "Dengue - NS1",
    category: "imunologia",
    description: "Antígeno NS1 do vírus da dengue",
    instructions: "Coletar até o 5º dia de sintomas",
  },
  {
    id: "dengue-igg-igm",
    name: "Dengue - IgG/IgM",
    category: "imunologia",
    description: "Sorologia para dengue",
    instructions: "Coletar a partir do 6º dia de sintomas",
  },
  {
    id: "dengue-sorotipo",
    name: "Dengue - Sorotipagem (PCR)",
    category: "imunologia",
    description: "Identificação do sorotipo da dengue",
    instructions: "Coletar até o 5º dia de sintomas",
  },
  {
    id: "zika-igm",
    name: "Zika Vírus - IgM",
    category: "imunologia",
    description: "Sorologia para Zika",
    instructions: "",
  },
  {
    id: "chikungunya-igm",
    name: "Chikungunya - IgM",
    category: "imunologia",
    description: "Sorologia para Chikungunya",
    instructions: "Coletar a partir do 5º dia de sintomas",
  },
  {
    id: "chikungunya-igg",
    name: "Chikungunya - IgG",
    category: "imunologia",
    description: "Sorologia para Chikungunya",
    instructions: "",
  },
  {
    id: "helicobacter-pylori-igg",
    name: "Helicobacter pylori - IgG",
    category: "imunologia",
    description: "Sorologia para H. pylori",
    instructions: "",
  },
  {
    id: "teste-h-pylori-urease",
    name: "Teste da Urease para H. pylori",
    category: "imunologia",
    description: "Teste rápido de urease",
    instructions: "",
  },
  {
    id: "antiglirodina",
    name: "Anticorpos Antigliadina (IgA e IgG)",
    category: "imunologia",
    description: "Rastreio de doença celíaca",
    instructions: "",
  },
  {
    id: "anti-endomisio",
    name: "Anticorpo Anti-Endomísio (IgA)",
    category: "imunologia",
    description: "Rastreio de doença celíaca",
    instructions: "",
  },
  {
    id: "anti-transglutaminase",
    name: "Antitransglutaminase (IgA)",
    category: "imunologia",
    description: "Rastreio de doença celíaca",
    instructions: "",
  },
  {
    id: "fator-reumatoide",
    name: "Fator Reumatoide",
    category: "imunologia",
    description: "Pesquisa de fator reumatoide",
    instructions: "",
  },
  {
    id: "anti-ccp",
    name: "Anti-CCP (Anticorpo Antipeptídeo Cíclico Citrulinado)",
    category: "imunologia",
    description: "Marcador de artrite reumatoide",
    instructions: "",
  },
  {
    id: "fana",
    name: "FANA (Fator Antinuclear)",
    category: "imunologia",
    description: "Pesquisa de anticorpos antinucleares",
    instructions: "",
  },
  {
    id: "anti-dna",
    name: "Anti-DNA (Anticorpo Anti-DNA de Cadeia Dupla)",
    category: "imunologia",
    description: "Marcador de lúpus eritematoso",
    instructions: "",
  },
  {
    id: "complemento-c3",
    name: "Complemento C3",
    category: "imunologia",
    description: "Dosagem de C3",
    instructions: "",
  },
  {
    id: "complemento-c4",
    name: "Complemento C4",
    category: "imunologia",
    description: "Dosagem de C4",
    instructions: "",
  },
  {
    id: "ige-total",
    name: "IgE Total",
    category: "imunologia",
    description: "Dosagem de imunoglobulina E",
    instructions: "",
  },
  {
    id: "ige-especifica",
    name: "IgE Específica (Painel Alérgico)",
    category: "imunologia",
    description: "Dosagem de IgE para alérgenos específicos",
    instructions: "",
  },
  {
    id: "iga",
    name: "IgA (Imunoglobulina A)",
    category: "imunologia",
    description: "Dosagem de imunoglobulina A",
    instructions: "",
  },
  {
    id: "igg",
    name: "IgG (Imunoglobulina G)",
    category: "imunologia",
    description: "Dosagem de imunoglobulina G",
    instructions: "",
  },
  {
    id: "igm",
    name: "IgM (Imunoglobulina M)",
    category: "imunologia",
    description: "Dosagem de imunoglobulina M",
    instructions: "",
  },
  {
    id: "beta-hcg",
    name: "Beta-hCG (Quantitativo)",
    category: "imunologia",
    description: "Gonadotrofina coriônica beta quantitativa",
    instructions: "",
  },
  {
    id: "beta-hcg-qualitativo",
    name: "Beta-hCG (Qualitativo)",
    category: "imunologia",
    description: "Teste de gravidez qualitativo",
    instructions: "",
  },

  // ═══════════════════════════════════════════════════════════
  // FUNÇÃO HEPÁTICA / HEPATITE
  // ═══════════════════════════════════════════════════════════
  {
    id: "funcao-hepatica",
    name: "Função Hepática Completa (TGO, TGP, GGT, FA, Bilirrubinas, Proteínas Totais)",
    category: "hepatite",
    description: "Painel hepático completo",
    instructions: "Jejum de 8h",
  },
  {
    id: "anti-hav-igm",
    name: "Anti-HAV IgM (Hepatite A)",
    category: "hepatite",
    description: "Sorologia para hepatite A aguda",
    instructions: "",
  },
  {
    id: "anti-hav-igg",
    name: "Anti-HAV IgG (Hepatite A)",
    category: "hepatite",
    description: "Imunidade contra hepatite A",
    instructions: "",
  },
  {
    id: "carga-viral-hbv",
    name: "Carga Viral HBV (DNA do HBV - PCR)",
    category: "hepatite",
    description: "DNA do HBV quantitativo",
    instructions: "",
  },
  {
    id: "anti-hev-igm",
    name: "Anti-HEV IgM (Hepatite E)",
    category: "hepatite",
    description: "Sorologia para hepatite E",
    instructions: "",
  },

  // ═══════════════════════════════════════════════════════════
  // CARDIOLOGIA
  // ═══════════════════════════════════════════════════════════
  {
    id: "ecg",
    name: "ECG (Eletrocardiograma de Repouso)",
    category: "cardiologia",
    description: "Eletrocardiograma de 12 derivações",
    instructions: "",
  },
  {
    id: "holter-24h",
    name: "Holter 24h",
    category: "cardiologia",
    description: "Monitoramento ECG ambulatorial 24h",
    instructions: "Usar por 24h consecutivas",
  },
  {
    id: "mapa-24h",
    name: "MAPA 24h (Monitorização Ambulatorial da Pressão Arterial)",
    category: "cardiologia",
    description: "Monitoramento da PA por 24h",
    instructions: "Usar por 24h consecutivas",
  },
  {
    id: "teste-ergometrico",
    name: "Teste Ergométrico (Teste de Esforço)",
    category: "cardiologia",
    description: "ECG de esforço em esteira ou bicicleta",
    instructions: "Jejum de 4h, roupa adequada para exercício",
  },
  {
    id: "ecocardiograma",
    name: "Ecocardiograma (Ecocardiografia Transtorácica)",
    category: "cardiologia",
    description: "Ultrassom cardíaco",
    instructions: "",
  },
  {
    id: "ecocardiograma-doppler",
    name: "Ecocardiograma com Doppler",
    category: "cardiologia",
    description: "Ecocardiografia com estudo Doppler",
    instructions: "",
  },
  {
    id: "bnp",
    name: "BNP (Peptídeo Natriurético Tipo B)",
    category: "cardiologia",
    description: "Marcador de insuficiência cardíaca",
    instructions: "",
  },
  {
    id: "nt-probnp",
    name: "NT-proBNP",
    category: "cardiologia",
    description: "Marcador de insuficiência cardíaca",
    instructions: "",
  },
  {
    id: "homocisteina",
    name: "Homocisteína",
    category: "cardiologia",
    description: "Fator de risco cardiovascular",
    instructions: "Jejum de 8h",
  },
  {
    id: "lipoproteina-a",
    name: "Lipoproteína (a)",
    category: "cardiologia",
    description: "Fator de risco cardiovascular",
    instructions: "Jejum de 12h",
  },
  {
    id: "apo-a1",
    name: "Apolipoproteína A1",
    category: "cardiologia",
    description: "Marcador de risco cardiovascular",
    instructions: "Jejum de 12h",
  },
  {
    id: "apo-b",
    name: "Apolipoproteína B",
    category: "cardiologia",
    description: "Marcador de risco cardiovascular",
    instructions: "Jejum de 12h",
  },

  // ═══════════════════════════════════════════════════════════
  // IMAGEM
  // ═══════════════════════════════════════════════════════════
  {
    id: "rx-torax",
    name: "Radiografia de Tórax (PA e Perfil)",
    category: "imagem",
    description: "Raio-X de tórax",
    instructions: "",
  },
  {
    id: "rx-torax-ap",
    name: "Radiografia de Tórax (AP)",
    category: "imagem",
    description: "Raio-X de tórax em AP",
    instructions: "",
  },
  {
    id: "rx-senos-da-face",
    name: "Radiografia de Seios da Face",
    category: "imagem",
    description: "Raio-X de seios paranasais",
    instructions: "",
  },
  {
    id: "rx-colar-cervical",
    name: "Radiografia de Coluna Cervical",
    category: "imagem",
    description: "Raio-X de coluna cervical (AP, perfil, oblíquas)",
    instructions: "",
  },
  {
    id: "rx-coluna-toracica",
    name: "Radiografia de Coluna Torácica",
    category: "imagem",
    description: "Raio-X de coluna torácica",
    instructions: "",
  },
  {
    id: "rx-coluna-lombar",
    name: "Radiografia de Coluna Lombar",
    category: "imagem",
    description: "Raio-X de coluna lombar (AP, perfil, oblíquas)",
    instructions: "",
  },
  {
    id: "rx-coluna-total",
    name: "Radiografia de Coluna Total (Panorâmica)",
    category: "imagem",
    description: "Raio-X panorâmico de coluna",
    instructions: "",
  },
  {
    id: "rx-abdome",
    name: "Radiografia de Abdome Agudo",
    category: "imagem",
    description: "Raio-X de abdome",
    instructions: "",
  },
  {
    id: "rx-pelve",
    name: "Radiografia de Pelve",
    category: "imagem",
    description: "Raio-X de bacia/pelve",
    instructions: "",
  },
  {
    id: "rx-quadril",
    name: "Radiografia de Quadril",
    category: "imagem",
    description: "Raio-X de quadril (AP e perfil)",
    instructions: "",
  },
  {
    id: "rx-joelho",
    name: "Radiografia de Joelho",
    category: "imagem",
    description: "Raio-X de joelho (AP, perfil, axial)",
    instructions: "",
  },
  {
    id: "rx-tornozelo",
    name: "Radiografia de Tornozelo",
    category: "imagem",
    description: "Raio-X de tornozelo",
    instructions: "",
  },
  {
    id: "rx-pe",
    name: "Radiografia de Pé",
    category: "imagem",
    description: "Raio-X de pé",
    instructions: "",
  },
  {
    id: "rx-mao",
    name: "Radiografia de Mão",
    category: "imagem",
    description: "Raio-X de mão",
    instructions: "",
  },
  {
    id: "rx-punho",
    name: "Radiografia de Punho",
    category: "imagem",
    description: "Raio-X de punho",
    instructions: "",
  },
  {
    id: "rx-cotovelo",
    name: "Radiografia de Cotovelo",
    category: "imagem",
    description: "Raio-X de cotovelo",
    instructions: "",
  },
  {
    id: "rx-ombro",
    name: "Radiografia de Ombro",
    category: "imagem",
    description: "Raio-X de ombro",
    instructions: "",
  },
  {
    id: "rx-costela",
    name: "Radiografia de Costelas",
    category: "imagem",
    description: "Raio-X de grade costal",
    instructions: "",
  },
  {
    id: "rx-clavicula",
    name: "Radiografia de Clavícula",
    category: "imagem",
    description: "Raio-X de clavícula",
    instructions: "",
  },
  {
    id: "rx-femur",
    name: "Radiografia de Fêmur",
    category: "imagem",
    description: "Raio-X de fêmur",
    instructions: "",
  },
  {
    id: "rx-perna",
    name: "Radiografia de Perna (Tíbia e Fíbula)",
    category: "imagem",
    description: "Raio-X de perna",
    instructions: "",
  },
  {
    id: "rx-antebraco",
    name: "Radiografia de Antebraço (Radio e Ulna)",
    category: "imagem",
    description: "Raio-X de antebraço",
    instructions: "",
  },
  {
    id: "rx-umero",
    name: "Radiografia de Úmero",
    category: "imagem",
    description: "Raio-X de úmero",
    instructions: "",
  },
  {
    id: "rx-dentaria",
    name: "Radiografia Panorâmica Dentária (Ortopantomografia)",
    category: "imagem",
    description: "Panorâmica dentária",
    instructions: "",
  },
  {
    id: "us-abdome-total",
    name: "Ultrassonografia de Abdome Total",
    category: "imagem",
    description: "US de fígado, vesícula, pâncreas, baço, rins e bexiga",
    instructions: "Jejum de 6-8h, bexiga cheia",
  },
  {
    id: "us-abdome-superior",
    name: "Ultrassonografia de Abdome Superior",
    category: "imagem",
    description: "US de fígado, vesícula, pâncreas e baço",
    instructions: "Jejum de 6-8h",
  },
  {
    id: "us-vias-biliares",
    name: "Ultrassonografia de Vias Biliares",
    category: "imagem",
    description: "US de vesícula e vias biliares",
    instructions: "Jejum de 6-8h",
  },
  {
    id: "us-renal",
    name: "Ultrassonografia Renal e Vias Urinárias",
    category: "imagem",
    description: "US de rins, ureteres e bexiga",
    instructions: "Bexiga cheia",
  },
  {
    id: "us-prostata",
    name: "Ultrassonografia de Próstata (Transretal)",
    category: "imagem",
    description: "US transretal de próstata",
    instructions: "Bexiga cheia",
  },
  {
    id: "us-prostata-transabdominal",
    name: "Ultrassonografia de Próstata (Transabdominal)",
    category: "imagem",
    description: "US transabdominal de próstata",
    instructions: "Bexiga cheia",
  },
  {
    id: "us-tireoide",
    name: "Ultrassonografia de Tireoide",
    category: "imagem",
    description: "US de tireoide",
    instructions: "",
  },
  {
    id: "us-mama",
    name: "Ultrassonografia de Mama",
    category: "imagem",
    description: "US de mama bilateral",
    instructions: "",
  },
  {
    id: "us-transvaginal",
    name: "Ultrassonografia Transvaginal",
    category: "imagem",
    description: "US transvaginal de útero e anexos",
    instructions: "Bexiga vazia",
  },
  {
    id: "us-obstetrica",
    name: "Ultrassonografia Obstétrica",
    category: "imagem",
    description: "US obstétrica",
    instructions: "",
  },
  {
    id: "us-morfologica",
    name: "Ultrassonografia Morfológica",
    category: "imagem",
    description: "US morfológica fetal",
    instructions: "",
  },
  {
    id: "us-doppler-vascular",
    name: "Ultrassonografia com Doppler Vascular",
    category: "imagem",
    description: "US Doppler de vasos",
    instructions: "",
  },
  {
    id: "doppler-carotidas",
    name: "Doppler de Carótidas e Vertebrais",
    category: "imagem",
    description: "US Doppler de artérias carótidas e vertebrais",
    instructions: "",
  },
  {
    id: "doppler-arterial-membros-inferiores",
    name: "Doppler Arterial de Membros Inferiores",
    category: "imagem",
    description: "US Doppler arterial de MMII",
    instructions: "",
  },
  {
    id: "doppler-venoso-membros-inferiores",
    name: "Doppler Venoso de Membros Inferiores",
    category: "imagem",
    description: "US Doppler venoso de MMII",
    instructions: "",
  },
  {
    id: "doppler-renal",
    name: "Doppler de Artérias Renais",
    category: "imagem",
    description: "US Doppler de artérias renais",
    instructions: "Jejum de 6h",
  },
  {
    id: "us-articulacao",
    name: "Ultrassonografia Articular",
    category: "imagem",
    description: "US de articulação (especificar)",
    instructions: "",
  },
  {
    id: "us-partes-moles",
    name: "Ultrassonografia de Partes Moles",
    category: "imagem",
    description: "US de nódulo/massa em partes moles",
    instructions: "",
  },
  {
    id: "tc-craneo",
    name: "Tomografia Computadorizada de Crânio",
    category: "imagem",
    description: "TC de crânio",
    instructions: "",
  },
  {
    id: "tc-torax",
    name: "Tomografia Computadorizada de Tórax",
    category: "imagem",
    description: "TC de tórax",
    instructions: "",
  },
  {
    id: "tc-abdome",
    name: "Tomografia Computadorizada de Abdome",
    category: "imagem",
    description: "TC de abdome total",
    instructions: "Jejum de 4h",
  },
  {
    id: "tc-coluna",
    name: "Tomografia Computadorizada de Coluna",
    category: "imagem",
    description: "TC de coluna (especificar segmento)",
    instructions: "",
  },
  {
    id: "rm-craneo",
    name: "Ressonância Magnética de Crânio",
    category: "imagem",
    description: "RM de crânio/encéfalo",
    instructions: "",
  },
  {
    id: "rm-coluna",
    name: "Ressonância Magnética de Coluna",
    category: "imagem",
    description: "RM de coluna (especificar segmento)",
    instructions: "",
  },
  {
    id: "rm-joelho",
    name: "Ressonância Magnética de Joelho",
    category: "imagem",
    description: "RM de joelho",
    instructions: "",
  },
  {
    id: "rm-ombro",
    name: "Ressonância Magnética de Ombro",
    category: "imagem",
    description: "RM de ombro",
    instructions: "",
  },
  {
    id: "rm-pelve",
    name: "Ressonância Magnética de Pelve",
    category: "imagem",
    description: "RM de pelve",
    instructions: "",
  },
  {
    id: "rm-abdome",
    name: "Ressonância Magnética de Abdome",
    category: "imagem",
    description: "RM de abdome",
    instructions: "Jejum de 4h",
  },
  {
    id: "mamografia",
    name: "Mamografia Bilateral",
    category: "imagem",
    description: "Mamografia diagnóstica ou de rastreio",
    instructions: "Não usar desodorante no dia",
  },
  {
    id: "densitometria-ossea",
    name: "Densitometria Óssea",
    category: "imagem",
    description: "DEXA de coluna lombar e fêmur",
    instructions: "Suspender cálcio 24h antes",
  },
  {
    id: "cintilografia-ossea",
    name: "Cintilografia Óssea",
    category: "imagem",
    description: "Cintilografia do esqueleto",
    instructions: "",
  },
  {
    id: "cintilografia-tireoide",
    name: "Cintilografia de Tireoide",
    category: "imagem",
    description: "Cintilografia tireoidiana",
    instructions: "",
  },
  {
    id: "cintilografia-miocardica",
    name: "Cintilografia Miocárdica (Perfusão)",
    category: "imagem",
    description: "Cintilografia de perfusão miocárdica",
    instructions: "Jejum de 4h, suspender beta-bloqueadores",
  },
  {
    id: "eletroencefalograma",
    name: "Eletroencefalograma (EEG)",
    category: "imagem",
    description: "EEG convencional",
    instructions: "Não suspender medicações, lavar cabelo",
  },
  {
    id: "espirometria",
    name: "Espirometria (Prova de Função Pulmonar)",
    category: "imagem",
    description: "Espirometria com broncodilatador",
    instructions: "Suspender broncodilatadores 6-12h antes",
  },

  // ═══════════════════════════════════════════════════════════
  // CITOLOGIA / ANATOMIA PATOLÓGICA
  // ═══════════════════════════════════════════════════════════
  {
    id: "papanicolau",
    name: "Citologia Oncótica (Papanicolau)",
    category: "citologia",
    description: "Preventivo de câncer de colo uterino",
    instructions: "Sem relação sexual 48h antes, sem uso de cremes vaginais",
  },
  {
    id: "colposcopia",
    name: "Colposcopia",
    category: "citologia",
    description: "Exame colposcópico do colo uterino",
    instructions: "",
  },
  {
    id: "biopsia-pele",
    name: "Biopsia de Pele (Anatomopatológico)",
    category: "citologia",
    description: "Exame anatomopatológico de lesão de pele",
    instructions: "",
  },
  {
    id: "pf-aspirado",
    name: "PAAF (Punção Aspirativa por Agulha Fina)",
    category: "citologia",
    description: "Citologia por punção aspirativa",
    instructions: "",
  },
  {
    id: "liquido-sinovial",
    name: "Análise de Líquido Sinovial (Artrocentese)",
    category: "citologia",
    description: "Exame de líquido articular",
    instructions: "",
  },
  {
    id: "liquido-pleural",
    name: "Análise de Líquido Pleural (Toracocentese)",
    category: "citologia",
    description: "Exame de líquido pleural",
    instructions: "",
  },
  {
    id: "liquido-ascitico",
    name: "Análise de Líquido Ascítico (Paracentese)",
    category: "citologia",
    description: "Exame de líquido ascítico",
    instructions: "",
  },
  {
    id: "liquor",
    name: "Análise de Líquido Cefalorraquidiano (LCR)",
    category: "citologia",
    description: "Exame de LCR (bioquímico, citológico, microbiológico)",
    instructions: "",
  },

  // ═══════════════════════════════════════════════════════════
  // OUTROS
  // ═══════════════════════════════════════════════════════════
  {
    id: "teste-alergia",
    name: "Teste de Prick (Teste Alérgico)",
    category: "outros",
    description: "Teste cutâneo de hipersensibilidade",
    instructions: "Suspender anti-histamínicos 7 dias antes",
  },
  {
    id: "teste-contato",
    name: "Teste de Contato (Patch Test)",
    category: "outros",
    description: "Teste de contato para dermatite",
    instructions: "",
  },
  {
    id: "teste-peptideo-c",
    name: "Teste do Pezinho (Triagem Neonatal)",
    category: "outros",
    description: "Triagem neonatal (TSH, fenilcetonúria, etc.)",
    instructions: "Coletar entre 48h-7 dias de vida",
  },
  {
    id: "teste-suor",
    name: "Teste do Suor (Cloro no Suor)",
    category: "outros",
    description: "Dosagem de cloro no suor",
    instructions: "",
  },
  {
    id: "teste-oculto",
    name: "Teste de Sangue Oculto Fecal (Imunoquímico)",
    category: "outros",
    description: "Pesquisa de sangue oculto por método imunoquímico",
    instructions: "Sem restrição dietética",
  },
  {
    id: "colonoscopia",
    name: "Colonoscopia",
    category: "outros",
    description: "Endoscopia de cólon",
    instructions: "Preparo intestinal prévio",
  },
  {
    id: "endoscopia-digestiva",
    name: "Endoscopia Digestiva Alta",
    category: "outros",
    description: "EDA (esôfago, estômago e duodeno)",
    instructions: "Jejum de 8h",
  },
  {
    id: "retossigmoidoscopia",
    name: "Retossigmoidoscopia",
    category: "outros",
    description: "Endoscopia de reto e sigmoide",
    instructions: "Preparo intestinal prévio",
  },
  {
    id: "teste-eradicao-h-pylori",
    name: "Teste de Erradicação do H. pylori (Teste Respiratório)",
    category: "outros",
    description: "Teste respiratório com ureia marcada",
    instructions: "Suspender IBP 14 dias e ATB 30 dias antes",
  },
];

export function searchExams(query: string): LabExam[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  return LAB_EXAMS.filter((e) => {
    const haystack = `${e.name} ${e.description} ${e.category}`.toLowerCase();
    return q.split(" ").every((token) => haystack.includes(token));
  }).slice(0, 12);
}

export function getExamById(id: string): LabExam | undefined {
  return LAB_EXAMS.find((e) => e.id === id);
}

export function getExamsByCategory(category: string): LabExam[] {
  return LAB_EXAMS.filter((e) => e.category === category);
}
