import type { Drug } from "./types";

export const DRUG_DB: Drug[] = [
  // ── Antibióticos (ATB) ─────────────────────────────────────────────
  {
    id: "amoxicilina-500",
    name: "Amoxicilina 500mg",
    form: "Cápsula",
    manufacturer: "EMS",
    type: "atb",
    flag: "ATB",
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 cápsula de 8/8h por 7 dias",
  },
  {
    id: "amoxicilina-clavulanato-875",
    name: "Amoxicilina + Clavulanato 875mg",
    form: "Comprimido",
    manufacturer: "Medley",
    type: "atb",
    flag: "ATB",
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido de 12/12h por 7-10 dias",
  },
  {
    id: "azitromicina-500",
    name: "Azitromicina 500mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "atb",
    flag: "ATB",
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido 1x/dia por 3-5 dias",
  },
  {
    id: "cefalexina-500",
    name: "Cefalexina 500mg",
    form: "Cápsula",
    manufacturer: "Neo Química",
    type: "atb",
    flag: "ATB",
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 cápsula de 6/6h por 7 dias",
  },
  {
    id: "nitrofurantoina-100",
    name: "Nitrofurantoína 100mg",
    form: "Cápsula",
    manufacturer: "Medley",
    type: "atb",
    flag: "ATB",
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 cápsula de 6/6h por 5-7 dias",
  },
  {
    id: "ciprofloxacino-500",
    name: "Ciprofloxacino 500mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "atb",
    flag: "ATB",
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido de 12/12h por 7 dias",
  },
  {
    id: "metronidazol-400",
    name: "Metronidazol 400mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "atb",
    flag: "ATB",
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido de 8/8h por 7 dias",
  },

  // ── Receita Simples ────────────────────────────────────────────────
  {
    id: "ibuprofeno-600",
    name: "Ibuprofeno 600mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido de 8/8h por 5 dias, com alimento",
  },
  {
    id: "paracetamol-750",
    name: "Paracetamol 750mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido de 6/6h se dor ou febre",
  },
  {
    id: "dipirona-500",
    name: "Dipirona 500mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido de 6/6h se dor ou febre",
  },
  {
    id: "omeprazol-20",
    name: "Omeprazol 20mg",
    form: "Cápsula",
    manufacturer: "EMS",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 cápsula em jejum, 30min antes do café da manhã",
  },
  {
    id: "atorvastatina-20",
    name: "Atorvastatina 20mg",
    form: "Comprimido",
    manufacturer: "Pfizer",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido à noite",
  },
  {
    id: "losartana-50",
    name: "Losartana 50mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido 1x/dia",
  },
  {
    id: "enalapril-10",
    name: "Enalapril 10mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido 1x/dia",
  },
  {
    id: "metformina-850",
    name: "Metformina 850mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido ao almoço e 1 ao jantar",
  },
  {
    id: "levotiroxina-50",
    name: "Levotiroxina 50mcg",
    form: "Comprimido",
    manufacturer: "Merck",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido em jejum, 30min antes do café da manhã",
  },
  {
    id: "fenazopiridina-100",
    name: "Fenazopiridina 100mg",
    form: "Comprimido",
    manufacturer: "Neo Química",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido de 8/8h por 2 dias",
  },
  {
    id: "prednisona-20",
    name: "Prednisona 20mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido pela manhã por 5 dias",
  },
  {
    id: "loratadina-10",
    name: "Loratadina 10mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "simples",
    flag: null,
    rxType: "Receita Simples",
    defaultPosology: "Tomar 1 comprimido 1x/dia",
  },

  // ── Controle Especial ──────────────────────────────────────────────
  {
    id: "clonazepam-2",
    name: "Clonazepam 2mg",
    form: "Comprimido",
    manufacturer: "Roche",
    type: "ctrl",
    flag: "B1",
    rxType: "Notificação Branca",
    defaultPosology: "Tomar ½ comprimido à noite. Não interromper abruptamente.",
  },
  {
    id: "diazepam-5",
    name: "Diazepam 5mg",
    form: "Comprimido",
    manufacturer: "Roche",
    type: "ctrl",
    flag: "B1",
    rxType: "Notificação Branca",
    defaultPosology: "Tomar 1 comprimido à noite se necessário",
  },
  {
    id: "zolpidem-10",
    name: "Zolpidem 10mg",
    form: "Comprimido",
    manufacturer: "Sanofi",
    type: "ctrl",
    flag: "B1",
    rxType: "Notificação Branca",
    defaultPosology: "Tomar 1 comprimido imediatamente antes de dormir",
  },
  {
    id: "codeina-30",
    name: "Codeína 30mg",
    form: "Comprimido",
    manufacturer: "Cristália",
    type: "ctrl",
    flag: "A3",
    rxType: "Notificação Branca",
    defaultPosology: "Tomar 1 comprimido de 6/6h se dor intensa",
  },
  {
    id: "tramadol-50",
    name: "Tramadol 50mg",
    form: "Cápsula",
    manufacturer: "Cristália",
    type: "ctrl",
    flag: "C1",
    rxType: "Notificação Branca",
    defaultPosology: "Tomar 1 cápsula de 8/8h se dor. Máx 400mg/dia.",
  },
  {
    id: "metilfenidato-10",
    name: "Metilfenidato 10mg",
    form: "Comprimido",
    manufacturer: "Novartis",
    type: "ctrl",
    flag: "A3",
    rxType: "Notificação Especial Amarela",
    defaultPosology: "Tomar 1 comprimido pela manhã e ½ ao meio-dia",
  },
  {
    id: "bupropiona-150",
    name: "Bupropiona 150mg",
    form: "Comprimido",
    manufacturer: "GSK",
    type: "ctrl",
    flag: "C1",
    rxType: "Notificação Branca",
    defaultPosology: "Tomar 1 comprimido pela manhã por 7 dias, depois 1 comprimido 2x/dia",
  },
  {
    id: "amitriptilina-25",
    name: "Amitriptilina 25mg",
    form: "Comprimido",
    manufacturer: "EMS",
    type: "ctrl",
    flag: "C1",
    rxType: "Notificação Branca",
    defaultPosology: "Tomar 1 comprimido à noite",
  },
];

export function searchDrugs(query: string): Drug[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  return DRUG_DB.filter((d) => {
    const haystack = `${d.name} ${d.form} ${d.manufacturer}`.toLowerCase();
    // Fuzzy: todos os tokens da query devem aparecer
    return q.split(" ").every((token) => haystack.includes(token));
  }).slice(0, 8);
}

export function getDrugById(id: string): Drug | undefined {
  return DRUG_DB.find((d) => d.id === id);
}
